name: CI
on: 
  push:
  schedule:
    - cron:  '0 1 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK 
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
      - run: dotnet tool install --global mlnet-linux-x64 && cd logicGP.Tests/logicGP.Tests && dotnet test --filter "TestCategory=FixedSeed"

